// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/phish-stats-api/internal/services/phishnet (interfaces: MapperI)

// Package phishnet is a generated GoMock package.
package phishnet

import (
	reflect "reflect"

	models "github.com/calebtracey/phish-stats-api/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMapperI is a mock of MapperI interface.
type MockMapperI struct {
	ctrl     *gomock.Controller
	recorder *MockMapperIMockRecorder
}

// MockMapperIMockRecorder is the mock recorder for MockMapperI.
type MockMapperIMockRecorder struct {
	mock *MockMapperI
}

// NewMockMapperI creates a new mock instance.
func NewMockMapperI(ctrl *gomock.Controller) *MockMapperI {
	mock := &MockMapperI{ctrl: ctrl}
	mock.recorder = &MockMapperIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapperI) EXPECT() *MockMapperIMockRecorder {
	return m.recorder
}

// PhishNetResponseToShowResponse mocks base method.
func (m *MockMapperI) PhishNetResponseToShowResponse(arg0 PNShowResponse) models.ShowResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhishNetResponseToShowResponse", arg0)
	ret0, _ := ret[0].(models.ShowResponse)
	return ret0
}

// PhishNetResponseToShowResponse indicates an expected call of PhishNetResponseToShowResponse.
func (mr *MockMapperIMockRecorder) PhishNetResponseToShowResponse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhishNetResponseToShowResponse", reflect.TypeOf((*MockMapperI)(nil).PhishNetResponseToShowResponse), arg0)
}
