// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/phish-stats-api/internal/services/phishnet (interfaces: ServiceI)

// Package phishnet is a generated GoMock package.
package phishnet

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceI is a mock of ServiceI interface.
type MockServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockServiceIMockRecorder
}

// MockServiceIMockRecorder is the mock recorder for MockServiceI.
type MockServiceIMockRecorder struct {
	mock *MockServiceI
}

// NewMockServiceI creates a new mock instance.
func NewMockServiceI(ctrl *gomock.Controller) *MockServiceI {
	mock := &MockServiceI{ctrl: ctrl}
	mock.recorder = &MockServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceI) EXPECT() *MockServiceIMockRecorder {
	return m.recorder
}

// GetShow mocks base method.
func (m *MockServiceI) GetShow(arg0 context.Context, arg1 string) (ShowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShow", arg0, arg1)
	ret0, _ := ret[0].(ShowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShow indicates an expected call of GetShow.
func (mr *MockServiceIMockRecorder) GetShow(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShow", reflect.TypeOf((*MockServiceI)(nil).GetShow), arg0, arg1)
}
